// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmployeeForm.Entity
{
    public partial class EmployeeLocation
    {
        public EmployeeLocation()
        {
            EmployeeInfo = new HashSet<EmployeeInfo>();
        }

        public int LocationId { get; set; }
        public string Employee_Work_Location { get; set; }
        public bool Is_Deleted { get; set; }
        public DateTime Updated_Time_stamp { get; set; }
        public DateTime Created_Time_stamp { get; set; }

        public virtual ICollection<EmployeeInfo> EmployeeInfo { get; set; }
    }
}